# Exploring the System {#ch-3}

- `ls` – List directory contents
- `file` – Determine file type
- `less` – View file contents

## Having More Fun with ls {-}

List multiple directories

```bash
$ ls ~ ./Desktop
```

Change the format of the output to reveal more detail.

```bash
$ ls -l
```

the `l` option to produce long format output, and the `t` option to sort the result by the file's modification time


```bash
$ ls -lt
```

add the long option “--reverse” to reverse the order of the sort.

```bash
$ ls -lt --reverse
```

*Note that command options, like filenames in Linux, are case-sensitive.*

## Common ls Options {-}

| Option | Long Option | Description |
| :--: | :--: | :-- |
| `-a` | `--all` | List all files, even those with names that begin with a period, which are normally not listed (that is, hidden). |
| `-A` | `--almost-all` | Like the -a option above except it does not list . (current directory) and .. (parent directory). |
| `-d` | `--directory` | Ordinarily, if a directory is specified, ls will list the contents of the directory, not the directory itself. Use this option in conjunction with the -l option to see details about the directory rather than its contents. |
| `-F` | `--classify` | This option will append an indicator character to the end of each listed name. For example, a forward slash (/) if the name is a directory. |
| `-h` | `--human-readable` | In long format listings, display file sizes in human readable format rather than in bytes. |
| `-l` |  | Display results in long format. |
| `-r` | `--reverse` | Display the results in reverse order. Normally, ls displays its results in ascending alphabetical order. |
| `-S` | | Sort results by file size. |
| `-t` | | Sort by modification time.|


## Determining a File's Type with file {-}

```bash
$ file picture.jpg
picture.jpg: JPEG image data, JFIF standard 1.01
```

## Viewing File Contents with less {-}

The `less` command is a program to view text files. Throughout our Linux system, there are many files that contain human-readable text. The `less` program provides a convenient way to examine them.

> **What Is “Text”?**
`r newLine()`
There are many ways to represent information on a computer. All methods involve defining a relationship between the information and some numbers that will be used to represent it. Computers, after all, only understand numbers and all data is converted to numeric representation.
`r newLine()``r newLine()`
Some of these representation systems are very complex (such as compressed video files), while others are rather simple. One of the earliest and simplest is called ASCII text. ASCII (pronounced "As-Key") is short for American Standard Code for Information Interchange. This is a simple encoding scheme that was first used on Teletype machines to map keyboard characters to numbers.
`r newLine()``r newLine()`
Text is a simple one-to-one mapping of characters to numbers. It is very compact. Fifty characters of text translates to fifty bytes of data. It is important to understand that text only contains a simple mapping of characters to numbers. It is not the same as a word processor document such as one created by Microsoft Word or LibreOffice Writer. Those files, in contrast to simple ASCII text, contain many non-text elements that are used to describe its structure and formatting. Plain ASCII text files contain only the characters themselves and a few rudimentary control codes such as tabs, carriage returns and line feeds.
`r newLine()``r newLine()`
Throughout a Linux system, many files are stored in text format and there are many Linux tools that work with text files. Even Windows recognizes the importance of this format. The well-known NOTEPAD.EXE program is an editor for plain ASCII text files.


Why would we want to examine text files? Because many of the files that contain system settings (called configuration files) are stored in this format, and being able to read them gives us insight about how the system works. In addition, some of the actual programs that the system uses (called scripts) are stored in this format.

The less command is used like this:

```bash
$ less filename
```

## less Commands {-}


| Command | Action |
| :-- | :-- |
| Page Up or b | Scroll back one page |
| Page Down or space | Scroll forward one page |
| Up arrow | Scroll up one line |
| Down arrow | Scrool down one line |
| G | Move to the end of the text |
| 1G of g | Move to the beginning of the text file |
| /*characters* | Search forward to the next occurrence of *characters* |
| n | Search for the next occurrence of the previous search |
| h | Display help screen |
| q | Quit `less` |



## Directories Found on Linux Systems {-}

| Directory | Comments |
| :-- | :-- |
| `/` | The root directory. Where everything begins. |
| `/bin` | Contains binaries (programs) that must be present for the system to boot and run.|
| `/boot` | Contains the Linux kernel, initial RAM disk image (for drivers needed at boot time), and the boot loader. `r newLine()``r newLine()` *Interesting files:* `r newLine()` - `/boot/grub/grub.conf` or `menu.lst`, which are used to configure the boot loader.`r newLine()`- `/boot/vmlinuz` (or something similar), the Linux kernel |
| `/dev` | This is a special directory that contains *device nodes*. “Everything is a file” also applies to devices. Here is where the kernel maintains a list of all the devices it understands. |
| `/etc` | The `/etc` directory contains all of the system-wide configuration files. It also contains a collection of shell scripts that start each of the system services at boot time. Everything in this directory should be readable text. `r newLine()` `r newLine()`Interesting files: While everything in `/etc` is interesting, here are some all-time favorites:`r newLine()`- `/etc/crontab`, a file that defines when automated jobs will run.`r newLine()`- `/etc/fstab`, a table of storage devices and their associated mount points.`r newLine()`- `/etc/passwd`, a list of the user accounts. |
| `/home` | In normal configurations, each user is given a directory in `/home`. Ordinary users can only write files in their home directories. This limitation protects the system from errant user activity.|
| `/lib` | Contains shared library files used by the core system programs. These are similar to dynamic link libraries (DLLs) in Windows. |
| `/lost+found` | Each formatted partition or device using a Linux file system, such as ext4, will have this directory. It is used in the case of a partial recovery from a file system corruption event. Unless something really bad has happened to our system, this directory will remain empty. |
| `/media` | On modern Linux systems the `/media` directory will contain the mount points for removable media such as USB drives, CD-ROMs, etc. that are mounted automatically at insertion. |
| `/mnt` | On older Linux systems, the `/mnt` directory contains mount points for removable devices that have been mounted manually. |
| `/opt` | The `/opt` directory is used to install “optional” software. This is mainly used to hold commercial software products that might be installed on the system. |
| `/proc` | The `/proc` directory is special. It's not a real file system in the sense of files stored on the hard drive. Rather, it is a virtual file system maintained by the Linux kernel. The “files” it contains are peepholes into the kernel itself. The files are readable and will give us a picture of how the kernel sees the computer. |
| `/root` | This is the home directory for the root account. |
| `/sbin` | This directory contains “system” binaries. These are programs that perform vital system tasks that are generally reserved for the superuser. |
| `/tmp` | The `/tmp` directory is intended for the storage of temporary, transient files created by various programs. Some configurations cause this directory to be emptied each time the system is rebooted. |
| `/usr` | The `/usr` directory tree is likely the largest one on a Linux system. It contains all the programs and support files used by regular users. |
| `/usr/bin` | `/usr/bin` contains the executable programs installed by the Linux distribution. It is not uncommon for this directory to hold thousands of programs. |
| `usr/local` | The `/usr/local` tree is where programs that are not included with the distribution but are intended for system-wide use are installed. Programs compiled from source code are normally installed in `/usr/local/bin`. On a newly installed Linux system, this tree exists, but it will be empty until the system administrator puts something in it. |
| `usr/sbin` | Contains more system administration programs. |
| `/usr/share` | `/usr/share` contains all the shared data used by programs in `/usr/bin`. This includes things such as default configuration files, icons, screen backgrounds, sound files, etc. |
| `/usr/share/doc` | Most packages installed on the system will include some kind of documentation. In `/usr/share/doc`, we will find documentation files organized by package. |
| `/var` | With the exception of `/tmp` and `/home`, the directories we have looked at so far remain relatively static, that is, their contents don't change. The `/var` directory tree is where data that is likely to change is stored. Various databases, spool files, user mail, etc. are located here. |
| `var/long` | `/var/log` contains log *files*, records of various system activity. These are important and should be monitored from time to time. The most useful ones are `/var/log/messages` and `/var/log/syslog`.`r newLine()`*Note*: that for security reasons on some systems only the superuser may view log files. |




