# Manipulating Files and Directories

At this point, we are ready for some real work! This chapter will introduce the following
commands:

- `cp` – Copy files and directories
- `mv` – Move/rename files and directories
- `mkdir` – Create directories
- `rm` – Remove files and directories
- `ln` – Create hard and symbolic links


How could we copy all the HTML files from one directory to another but only copy files that do not exist in the destination directory or are newer than the versions in the destination directory? It's pretty hard with a file manager but pretty easy with the command line.


```bash
$ cp -u *.html destination
```

## Wildcards {.unnumbered}

Using wildcards (which is also known as *globbing*) allows us to select filenames based on patterns of characters.

| Wildcard | Meaning |
| :-- | :-- |
| `*` | Matches any characters |
| `?` | Matches any single character |
| [characters] | Matches any character that is a member of the set *characters* |
| [!characters] | Matches any character that is not a member of the set *characters* |
| [[:class:]] | Matches any character that is a member of the specified *class* |


**Commonly Used Character Classes**


| Charater Class | Meaning |
| :-- | :-- |
| [:alnum:] | Matches any alphanumeric character |
| [:alpha:] | Matches any alphabetic character |
| [:digit:] | Matches any numeral |
| [:lower:] | Matches any lowercase letter |
| [:upper:] | Matches any uppercase letter |


Using wildcards makes it possible to construct sophisticated selection criteria for filenames.


**Wildcard Examples**

| Pattern | Match |
| :-- | :-- |
| `*` | All files |
| `g*` | Any file beginning with “g” |
| `b*.txt` | Any file beginning with “b” followed by any characters and ending with “.txt” |
| `Data???` | Any file beginning with “Data” followed by exactly three characters |
| `[abc]*` | Any file beginning with either an “a”, a “b”, or a “c” |
| `BACKUP.[0-9][0-9][0-9]` | Any file beginning with “BACKUP.” followed by exactly three numerals |
| `[[:upper:]]*` | Any file beginning with an uppercase letter |
| `[![:digit:]]*` | Any file not beginning with a numeral |
| `*[[:lower:]123]` | Any file ending with a lowercase letter or the numerals “1”, “2”, or “3” |

Wildcards can be used with any command that accepts filenames as arguments.


> **Character Ranges**
`r newLine()`
If you are coming from another Unix-like environment or have been reading some other books on this subject, you may have encountered the [A-Z] and [a-z] character range notations. These are traditional Unix notations and worked in older versions of Linux as well. They can still work, but you have to be careful with them because they will not produce the expected results unless properly configured. For now, you should avoid using them and use character classes instead.


## mkdir - Create Directories {.unnumbered}

The `mkdir` command is used to create directories. It works like this:

```bash
$ mkdir directory...
```

A note on notation: When three periods follow an argument in the description of a command (as above), it means that the argument can be repeated, thus the following command:

```bash
$ mkdir dir1
```

would create a single directory named dir1, while the following:

```bash
$ mkdir dir1 dir2 dir3
```

would create three directories named dir1, dir2, and dir3.



## cp – Copy Files and Directories {.unnumbered}

The cp command copies files or directories. It can be used two different ways. The following:

```bash
$ cp item1 item2
```

copies the single file or directory item1 to the file or directory item2 and the following:

```bash
$ cp item... directory
```

copies multiple items (either files or directories) into a directory.

### Useful Options and Examples {.unnumbered}

**Options**

| Option | Long Option | Meaning |
| :-- | :-- | :-- |
| `-a` | `--archive` | Copy the files and directories and all of their attributes, including ownerships and permissions. Normally, copies take on the default attributes of the user performing the copy. | 
| `-i` | `--interactive` | Before overwriting an existing file, prompt the user for confirmation. **If this option is not specified, cp will silently (meaning there will be no warning) overwrite files.** |
| `-r` | `--recursive` | Recursively copy directories and their contents. This option (or the -a option) is required when copying directories. |
| `-u` | | `--update` | When copying files from one directory to another, only copy files that either don't exist or are newer than the existing corresponding files, in the destination directory. This is useful when copying large numbers of files as it skips files that don't need to be copied. |
| `-v` | `--verbose` | Display informative messages as the copy is performed. |

**Examples**

| Command | Result |
| :-- | :-- |
| `cp file1 file1` | Copy file1 to file2. **If file2 exists, it is overwritten with the contents of file1**. If file2 does not exist, it is created |
| `cp -i file1 file2` | Same as previous command, except that if file2 exists, the user is prompted before it is overwritten.|
| `cp file1 file2 dir1` | Copy file1 and file2 into directory dir1. The directory dir1 must already exist. |
| `cp dir1/* dir2` | Using a wildcard, copy all the files in dir1 into dir2. The directory dir2 must already exist. |
| `cp -r dir1 dir2` | Copy the contents of directory dir1 to directory dir2. If directory dir2 does not exist, it is created and, after the copy, will contain the same contents as directory dir1.`r newLine()`If directory dir2 does exist, then directory dir1 (and its contents) will be copied into dir2.|



## mv – Move and Rename Files {.unnumbered}

The mv command performs both file moving and file renaming, depending on how it is used. In either case, the original filename no longer exists after the operation. mv is used in much the same way as cp, as shown here:


```bash
$ mv item1 item2
```

to move or rename the file or directory item1 to item2 or:


```bash
$ mv item... directory
```

to move one or more items from one directory to another.

### Useful Options and Examples {.unnumbered}

**Options**

| Option | Long Option | Meaning |
| :-- | :-- | :-- |
| `-i` | `--interact` | Before overwriting an existing file, prompt the user for confirmation. **If this option is not specified, mv will silently overwrite files.** |
| `-u` | `--update` | When moving files from one directory to another, only move files that either don't exist, or are newer than the existing corresponding files in the destination directory. |
| `-v` | `--verbose` | Display informative messages as the move is performed. |

## rm – Remove Files and Directories {.unnumbered}

The rm command is used to remove (delete) files and directories, as shown here:

```bash
$ rm item...
```

where item is one or more files or directories.



> **Be Careful with rm!**
`r newLine()`
Unix-like operating systems such as Linux do not have an undelete command.
Once you delete something with rm, it's gone. Linux assumes you're smart and
you know what you're doing.
`r newLine()``r newLine()`
Be particularly careful with wildcards. Consider this classic example. Let's say
you want to delete just the HTML files in a directory. To do this, you type the following:
`r newLine()``r newLine()`
rm *.html
`r newLine()``r newLine()`
This is correct, but if you accidentally place a space between the * and the
.html like so:
`r newLine()``r newLine()`
rm * .html
`r newLine()``r newLine()`
the rm command will delete all the files in the directory and then complain that
there is no file called .html.
`r newLine()``r newLine()`
**Here is a useful tip**: whenever you use wildcards with rm (besides carefully
checking your typing!), test the wildcard first with ls. This will let you see the
files that will be deleted. Then press the up arrow key to recall the command and
replace ls with rm.


**Options**

| Option | Long Option | Meaning |
| :-- | :-- | :-- |
| `-i` | `--interactive` | Before deleting an existing file, prompt the user for confirmation. If this option is not specified, rm will silently delete files. |
| `-r` | `--recursive` | Recursively delete directories. This means that if a directory being deleted has subdirectories, delete them too. To delete a directory, this option must be specified. |
| `-f` | `--force` | Ignore nonexistent files and do not prompt. This overrides the --interactive option. |
| `-v` | `--verbose` | Display informative messages as the deletion is performed. |


## ln – Create Links {.unnumbered}

The ln command is used to create either hard or symbolic links. It is used in one of two
ways. The following creates a hard link:


```bash
$ ln file link
```

The following creates a symbolic link:


```bash
$ ln -s file link
```

to create a symbolic link where item is either a file or a directory.

### Hard Links {.unnumbered}

y default, every file has a single hard link that gives the file its name.
When we create a hard link, we create an additional directory entry for a file. Hard links
have two important limitations:

1. A hard link cannot reference a file outside its own file system. This means a link cannot reference a file that is not on the same disk partition as the link itself.
2. A hard link may not reference a directory.


A hard link is indistinguishable from the file itself. Unlike a symbolic link, when we list a
directory containing a hard link we will see no special indication of the link. When a hard
link is deleted, the link is removed but the contents of the file itself continue to exist (that
is, its space is not deallocated) until all links to the file are deleted.

It is important to be aware of hard links because you might encounter them from time to
time, but modern practice prefers symbolic links.


### Symbolic Links {.unnumbered}

Symbolic links were created to overcome the limitations of hard links. Symbolic links work by creating a special type of file that contains a text pointer to the referenced file or directory. In this regard, they operate in much the same way as a Windows shortcut, though of course they predate the Windows feature by many years.

A file pointed to by a symbolic link, and the symbolic link itself are largely indistinguishable from one another. For example, if we write something to the symbolic link, the referenced file is written to. However when we delete a symbolic link, only the link is deleted, not the file itself. If the file is deleted before the symbolic link, the link will continue to exist but will point to nothing. In this case, the link is said to be broken. In many implementations, the ls command will display broken links in a distinguishing color, such as red, to reveal their presence.

