# Working with Commands

- `type` – Indicate how a command name is interpreted
- `which` – Display which executable program will be executed
- `help` – Get help for shell builtins
- `man` – Display a command's manual page
- `apropos` – Display a list of appropriate commands
- `info` – Display a command's info entry
- `whatis` – Display one-line manual page descriptions
- `alias` – Create an alias for a command

## What Exactly Are Commands? {.unnumbered}

A command can be one of four different things:

1. **An executable program** like all those files we saw in `/usr/bin`. Within this category, programs can be *compiled binaries* such as programs written in C and C++, or programs written in *scripting languages* such as the shell, Perl, Python, Ruby, and so on.
2. **A command built into the shell itself**. bash supports a number of commands internally called *shell builtins*. The `cd` command, for example, is a shell builtin.
3. **A shell function**. Shell functions are miniature shell scripts incorporated into the *environment*. We will cover configuring the environment and writing shell functions in later chapters, but for now, just be aware that they exist.
4. **An alias**. Aliases are commands that we can define ourselves, built from other commands.



## Identifying Commands {.unnumbered}

It is often useful to know exactly which of the four kinds of commands is being used and
Linux provides a couple of ways to find out.

### type – Display a Command's Type {.unnumbered}

The type command is a shell builtin that displays the kind of command the shell will
execute, given a particular command name. It works like this:

```bash
$ type command
```

where “command” is the name of the command we want to examine. Here are some ex-
amples:

```bash
$ type type
type is a shell builtin
$ type ls
ls is aliased to 'ls --color=tty'
$ type cp
cp is /bin/cp
```

### which – Display an Executable's Location {.unnumbered}

Sometimes there is more than one version of an executable program installed on a system. While this is not common on desktop systems, it's not unusual on large servers. To
determine the exact location of a given executable, the which command is used.

```bash
[me@linuxbox ~]$ which ls
/bin/ls
```

which only works for executable programs, not builtins nor aliases that are substitutes
for actual executable programs.


## Getting a Command's Documentation {.unnumbered}

bash has a built-in help facility available for each of the shell builtins. To use it, type
“help” followed by the name of the shell builtin.


```bash
$ help cd
cd: cd [-L|[-P [-e]] [-@]] [dir]
    Change the shell working directory.
    
    Change the current directory to DIR.  The default DIR is the value of the
    HOME shell variable.
    
    The variable CDPATH defines the search path for the directory containing
    DIR.  Alternative directory names in CDPATH are separated by a colon (:).
    A null directory name is the same as the current directory.  If DIR begins
    with a slash (/), then CDPATH is not used.
    
    If the directory is not found, and the shell option 'cdable_vars' is set,
    the word is assumed to be  a variable name.  If that variable has a value,
    its value is used for DIR.
    
    Options:
      -L	force symbolic links to be followed: resolve symbolic
    		links in DIR after processing instances of '..'
      -P	use the physical directory structure without following
    		symbolic links: resolve symbolic links in DIR before
    		processing instances of '..'
      -e	if the -P option is supplied, and the current working
    		directory cannot be determined successfully, exit with
    		a non-zero status
      -@	on systems that support it, present a file with extended
    		attributes as a directory containing the file attributes
    
    The default is to follow symbolic links, as if '-L' were specified.
    '..' is processed by removing the immediately previous pathname component
    back to a slash or the beginning of DIR.
    
    Exit Status:
    Returns 0 if the directory is changed, and if $PWD is set successfully when
    -P is used; non-zero otherwise.
```


A note on notation: When square brackets appear in the description of a command's syntax, they indicate optional items. A vertical bar character indicates mutually exclusive
items. In the case of the cd command above:

    cd [-L|[-P[-e]]] [dir]

This notation says that the command cd may be followed optionally by either a “-L” or a
“-P” and further, if the “-P” option is specified the “-e” option may also be included followed by the optional argument “dir”.

### --help – Display Usage Information {.unnumbered}

Many executable programs support a “--help” option that displays a description of the
command's supported syntax and options. For example:

```bash
$ mkdir --help
Usage: mkdir [OPTION]... DIRECTORY...
Create the DIRECTORY(ies), if they do not already exist.

Mandatory arguments to long options are mandatory for short options too.
  -m, --mode=MODE   set file mode (as in chmod), not a=rwx - umask
  -p, --parents     no error if existing, make parent directories as needed
  -v, --verbose     print a message for each created directory
  -Z                   set SELinux security context of each created directory
                         to the default type
      --context[=CTX]  like -Z, or if CTX is specified then set the SELinux
                         or SMACK security context to CTX
      --help     display this help and exit
      --version  output version information and exit

GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
Full documentation at: <https://www.gnu.org/software/coreutils/mkdir>
or available locally via: info '(coreutils) mkdir invocation'
```

## Creating Our Own Commands with alias {.unnumbered}

- 1. Check is alias already exists
  - Ex. `type test`
- 2. Make alias command: `alias name='string'`
  - Ex. `alias foo='cd home; ls; cd -'`


Create Alias:

```bash
$ alias foo='cd ~/Desktop; ls; cd -'
```

Remove Alias:
```bash
$ unalias foo
```



View all existing alias:

```bash
$ alias
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
```






