# See the World as the Shell Sees It

### Expansion

Each time we type a command and press the Enter key, bash performs several substitutions upon the text before it carries out our command.

```bash
$ echo This is a test
This is a test
```

```bash
$ echo *
Desktop Documents ls-output.txt Music Pictures Public Templates Videos
```


So what just happened? Why didn't echo print \*? As we recall from our work with wildcards, 
the \* character means match any characters in a filename, but what we didn't see in
our original discussion was how the shell does that. The simple answer is that the shell
expands the \* into something else (in this instance, the names of the files in the current
working directory) before the echo command is executed. When the Enter key is
pressed, the shell automatically expands any qualifying characters on the command line
before the command is carried out, so the echo command never saw the \*, only its expanded result. 
Knowing this, we can see that echo behaved as expected.



#### Pathname Expansion

The mechanism by which wildcards work is called pathname expansion.

Given a home directory that looks like this:

```bash
$ ls
Desktop ls-output.txt Pictures Templates Documents Music
```


we could carry out the following expansions:

```bash
$ echo D*
Desktop Documents
```

and this:

```bash
$ echo *s
Documents Pictures Templates Videos
```


or even this:

```bash
$ echo [[:upper:]]*
Desktop Documents Music Pictures Public Templates Videos
```



and looking beyond our home directory, we could do this:

```bash
$ echo /usr/*/share
/usr/kerberos/share /usr/local/share
```



> **Pathname Expansion of Hidden Files**
`r newLine()`
As we know, filenames that begin with a period character are hidden. Pathname
expansion also respects this behavior. An expansion such as the following does
not reveal hidden files.
`r newLine()``r newLine()`
echo *
`r newLine()``r newLine()`
It might appear at first glance that we could include hidden files in an expansion
by starting the pattern with a leading period, like this:
`r newLine()``r newLine()`
echo .*
`r newLine()``r newLine()`
It almost works. However, if we examine the results closely, we will see that the
names . and .. will also appear in the results. Because these names refer to the
current working directory and its parent directory, using this pattern will likely
produce an incorrect result. We can see this if we try the following command:
`r newLine()``r newLine()`
ls -d .* | less
`r newLine()``r newLine()`
To better perform pathname expansion in this situation, we have to employ a
more specific pattern.
`r newLine()``r newLine()`
echo .[!.]*
`r newLine()``r newLine()`
This pattern expands into every filename that begins with only one period 
followed by any other characters. This will work correctly with most hidden files
(though it still won't include filenames with multiple leading periods). The ls
command with the -A option (“almost all”) will provide a correct listing of hidden files.
`r newLine()``r newLine()`
ls -A


#### Tilde Expansion (~)

As we may recall from our introduction to the cd command, the tilde character (~) has a
special meaning.

```bash
$ echo ~
/home/me
```



#### Arithmetic Expansion
The shell allows arithmetic to be performed by expansion. This allows us to use the shell
prompt as a calculator.

```bash
$ echo $((2 + 2))
4
```


Arithmetic expansion uses the following form:

    $((expression))

where expression is an arithmetic expression consisting of values and arithmetic operators.

Arithmetic expansion supports only integers (whole numbers, no decimals) but can perform quite a number of different operations.


```bash
$ echo Five divided by two equals $((5/2))
Five divided by two equals 2
```


#### Brace Expansion
Perhaps the strangest expansion is called brace expansion. With it, we can create multiple
text strings from a pattern containing braces. Here's an example:

```bash
$ echo Front-{A,B,C}-Back
Front-A-Back Front-B-Back Front-C-Back
$ echo Number_{1..5}
Number_1 Number_2 Number_3 Number_4 Number_5
$ echo {01..15}
01 02 03 04 05 06 07 08 09 10 11 12 13 14 15
echo {001..15}
001 002 003 004 005 006 007 008 009 010 011 012 013 014 015
$ echo {Z..A}
Z Y X W V U T S R Q P O N M L K J I H G F E D C B A
$ echo a{A{1,2},B{3,4}}b
aA1b aA2b aB3b aB4b
```
So, what is this good for?

```bash
$ mkdir {2007..2009}-{01..12}
$ ls
2007-01 2007-07 2008-01 2008-07 2009-01 2009-07
2007-02 2007-08 2008-02 2008-08 2009-02 2009-08
2007-03 2007-09 2008-03 2008-09 2009-03 2009-09
2007-04 2007-10 2008-04 2008-10 2009-04 2009-10
2007-05 2007-11 2008-05 2008-11 2009-05 2009-11
2007-06 2007-12 2008-06 2008-12 2009-06 2009-12
```


#### Parameter Expansion

the variable named
USER contains our username. To invoke parameter expansion and reveal the contents of
USER we would do this:


```bash
$ echo $USER
me
```


To see a list of available variables, try this:

```bash
$ printenv | less
```


#### Command Substitution

Command substitution allows us to use the output of a command as an expansion.


```bash
$ echo $(ls)
Desktop Documents ls-output.txt Music Pictures Public Templates
Videos
```

One of my favorites goes something like this:

```bash
$ ls -l $(which cp)
-rwxr-xr-x 1 root root 71516 2007-12-05 08:58 /bin/cp
```

Here we passed the results of which cp as an argument to the ls command, thereby getting the listing of the cp program without having to know its full pathname. We are
not limited to just simple commands. Entire pipelines can be used (only partial output is
shown here):

```bash
$ file $(ls -d /usr/bin/* | grep zip)
/usr/bin/bunzip2:   symbolic link to 'bzip2'
```



In this example, the results of the pipeline became the argument list of the file command.


There is an alternate syntax for command substitution in older shell programs that is also
supported in bash. It uses backquotes instead of the dollar sign and parentheses.


```bash
$ ls -l `which cp`
-rwxr-xr-x 1 root root 71516 2007-12-05 08:58 /bin/cp
```

### Quoting

The shell provides
a mechanism called quoting to selectively suppress unwanted expansions.

#### Double Quotes

The first type of quoting we will look at is double quotes. If we place text inside double
quotes, all the special characters used by the shell lose their special meaning and are
treated as ordinary characters. The exceptions are $, \ (backslash), and ` (back-quote).
This means that word-splitting, pathname expansion, tilde expansion, and brace expansion 
are suppressed, but parameter expansion, arithmetic expansion, and command substitution 
are still carried out. Using double quotes, we can cope with filenames containing
embedded spaces.


```bash
$ ls -l two words.txt
ls: cannot access two: No such file or directory
ls: cannot access words.txt: No such file or directory
```


By using double quotes, we stop the word-splitting and get the desired result; further, we
can even repair the damage.


```bash
$ ls -l "two words.txt"
-rw-rw-r-- 1 me  me  18 2016-02-20 13:03 two words.txt
$ mv "two words.txt" two_words.txt
```


Remember, parameter expansion, arithmetic expansion, and command substitution still
take place within double quotes.

```bash
$ echo "$USER $((2+2)) $(cal)"
me 4    February 2019
Su Mo Tu We Th Fr Sa
                1 2
    3 4 5 6 7 8 9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29
```


#### Single Quotes

If we need to suppress all expansions, we use single quotes. Here is a comparison of unquoted, double quotes, and single quotes:


```bash
$ echo text ~/*.txt {a,b} $(echo foo) $((2+2)) $USER
text /home/me/ls-output.txt a b foo 4 me
$ echo "text ~/*.txt {a,b} $(echo foo) $((2+2)) $USER"
text ~/*.txt {a,b} foo 4 me
$ echo 'text ~/*.txt {a,b} $(echo foo) $((2+2)) $USER'
text ~/*.txt {a,b} $(echo foo) $((2+2)) $USER
```

#### Escaping Characters

Sometimes we want to quote only a single character. To do this, we can precede a character with a backslash, which in this context is called the escape character. Often this is
done inside double quotes to selectively prevent an expansion.


```bash
$ echo "The balance for user $USER is: \$5.00"
The balance for user me is: $5.00
```













